### ISSUE TITLE
todo: add linux support

### ISSUE THREAD

**Issue by stevenmiller888** [stevenmiller888/intruder#2]
- Use [airodump](http://www.aircrack-ng.org/doku.php?id=airodump-ng) to sniff packets
- Use `iwlist scan` to list available networks

**Comment by vshabelnyk** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by manV** [comment]
+1

**Comment by stevenmiller888** [comment]
I haven't had a chance to test it out yet, but the [add/linux](/stevenmiller888/intruder/tree/add/linux) branch _might_ be working on Linux.

You can try cloning this branch and running the following:

```
Intruder()
  .on('attempt', function(ivs) {
    console.log(ivs);
  })
  .crack(SSID, function(err, key) {
    if (err) throw err;
    console.log(key);
  });
```

If you get a chance to try that, let me know if it works for you.

**Comment by stevenmiller888** [comment]
Just merged the `add/linux` branch into master. Feel free to reopen if the `master` branch isn't working for you.
