### ISSUE TITLE
network not found on Windows

### ISSUE THREAD

**Issue by raphaklaus** [stevenmiller888/intruder#7]
Hello, I'm getting the "network not found" on Windows 10. Is aircrack-ng mandatory to run the `intrude.crack`?

**Comment by stevenmiller888** [comment]
Yes, `aircrack-ng` is mandatory for Intruder to work. Intruder is really just a Node.js wrapper over aircrack-ng.

**Comment by raphaklaus** [comment]
I see.

Would you mind if I fork and enhance this repo documentation?

**Comment by stevenmiller888** [comment]
Not at all! In fact, I welcome it :)
